name: Deploy with Self-Hosted Runner

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted  # Uses the EC2 runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to EC2
        run: |
          cd /var/www/html
          git pull origin main
          sudo systemctl restart apache2
